<?php
$this->device_links['SMegaD2WmRelays']=array(
    array (
        'LINK_NAME'=>'relay_d2_switch',
        'LINK_TITLE'=>LANG_DEVICES_LINK_SENSOR_PASS_BATTERY,
        'LINK_DESCRIPTION'=>LANG_DEVICES_LINK_SENSOR_PASS_BATTERY_DESCRIPTION,
        'TARGET_CLASS'=>'SSensors',
    ),
    array(
            'LINK_NAME'=>'MegaD2Wm_switch',
            'LINK_TITLE'=>LANG_DEVICES_LINK_ZONA_SWITCH,
            'LINK_DESCRIPTION'=>LANG_DEVICES_LINK_ZONA_SWITCH_DESCRIPTION,
            'TARGET_CLASS'=>'SControllers,SDevices,SSensors',
            'PARAMS'=>array(
                array(
                    'PARAM_NAME'=>'invert_status',
                    'PARAM_TITLE'=>LANG_DEVICES_LINK_ZONA_INVERT,
                    'PARAM_TYPE'=>'select',
                    'PARAM_OPTIONS'=>array(
                        array('TITLE'=>LANG_NO,'VALUE'=>'0'),
                        array('TITLE'=>LANG_YES,'VALUE'=>'1'),
                        array('TITLE'=>LANG_DEVICES_LINK_ZONA_AUTO,'VALUE'=>'2')
                    )
                ),
                array(
                'PARAM_NAME'=>'action_type',
                'PARAM_TITLE'=>LANG_DEVICES_LINK_ACTION_TYPE,
                'PARAM_TYPE'=>'select',
                'PARAM_OPTIONS'=>array(
                    array('TITLE'=>LANG_DEVICES_LINK_TYPE_TURN_ON,'VALUE'=>'turnon'),
                    array('TITLE'=>LANG_DEVICES_LINK_TYPE_TURN_OFF,'VALUE'=>'turnoff'),
                    array('TITLE'=>LANG_DEVICES_LINK_TYPE_SWITCH,'VALUE'=>'switch'),
                    array('TITLE'=>'turnOnAuto','VALUE'=>'turnOnAuto')
                    )
                ),
            )
        ),
    array(
        'LINK_NAME'=>'switch_it',
        'LINK_TITLE'=>LANG_DEVICES_LINK_SWITCH_IT,
        'LINK_DESCRIPTION'=>LANG_DEVICES_LINK_SWITCH_IT_DESCRIPTION,
        'TARGET_CLASS'=>'SControllers',
        'PARAMS'=>array(
            array(
                'PARAM_NAME'=>'action_type',
                'PARAM_TITLE'=>LANG_DEVICES_LINK_ACTION_TYPE,
                'PARAM_TYPE'=>'select',
                'PARAM_OPTIONS'=>array(
                    array('TITLE'=>LANG_DEVICES_LINK_TYPE_TURN_ON,'VALUE'=>'turnon'),
                    array('TITLE'=>LANG_DEVICES_LINK_TYPE_TURN_OFF,'VALUE'=>'turnoff'),
                    array('TITLE'=>LANG_DEVICES_LINK_TYPE_SWITCH,'VALUE'=>'switch')
                    )
            ),
            array(
                'PARAM_NAME'=>'action_delay',
                'PARAM_TITLE'=>LANG_DEVICES_LINK_SWITCH_IT_PARAM_ACTION_DELAY,
                'PARAM_TYPE'=>'num'
            )
        )
    ),
);
